
package com.fiap.exemplos.ws2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlunoWebAuth", targetNamespace = "http://ws2.exemplos.fiap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlunoWebAuth {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticado", targetNamespace = "http://ws2.exemplos.fiap.com/", className = "com.fiap.exemplos.ws2.Autenticado")
    @ResponseWrapper(localName = "autenticadoResponse", targetNamespace = "http://ws2.exemplos.fiap.com/", className = "com.fiap.exemplos.ws2.AutenticadoResponse")
    @Action(input = "http://ws2.exemplos.fiap.com/AlunoWebAuth/autenticadoRequest", output = "http://ws2.exemplos.fiap.com/AlunoWebAuth/autenticadoResponse")
    public Boolean autenticado(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param senha
     * @param usuario
     * @param parameters
     * @return
     *     returns com.fiap.exemplos.ws2.ListarResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "listarResponse", targetNamespace = "http://ws2.exemplos.fiap.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws2.exemplos.fiap.com/AlunoWebAuth/listarRequest", output = "http://ws2.exemplos.fiap.com/AlunoWebAuth/listarResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws2.exemplos.fiap.com/AlunoWebAuth/listar/Fault/Exception")
    })
    public ListarResponse listar(
        @WebParam(name = "listar", targetNamespace = "http://ws2.exemplos.fiap.com/", partName = "parameters")
        Listar parameters,
        @WebParam(name = "Usuario", targetNamespace = "http://ws2.exemplos.fiap.com/", header = true, partName = "Usuario")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://ws2.exemplos.fiap.com/", header = true, partName = "Senha")
        String senha)
        throws Exception_Exception
    ;

    /**
     * 
     * @param senha
     * @param usuario
     * @param parameters
     * @return
     *     returns com.fiap.exemplos.ws2.NovoResponse
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "novoResponse", targetNamespace = "http://ws2.exemplos.fiap.com/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://ws2.exemplos.fiap.com/AlunoWebAuth/novoRequest", output = "http://ws2.exemplos.fiap.com/AlunoWebAuth/novoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws2.exemplos.fiap.com/AlunoWebAuth/novo/Fault/Exception")
    })
    public NovoResponse novo(
        @WebParam(name = "novo", targetNamespace = "http://ws2.exemplos.fiap.com/", partName = "parameters")
        Novo parameters,
        @WebParam(name = "Usuario", targetNamespace = "http://ws2.exemplos.fiap.com/", header = true, partName = "Usuario")
        String usuario,
        @WebParam(name = "Senha", targetNamespace = "http://ws2.exemplos.fiap.com/", header = true, partName = "Senha")
        String senha)
        throws Exception_Exception
    ;

}
