
package com.fiap.exemplos.ws2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlunoWebAuthService", targetNamespace = "http://ws2.exemplos.fiap.com/", wsdlLocation = "http://l2901micro04:8080/Exemplo3/AlunoWebAuthService?wsdl")
public class AlunoWebAuthService
    extends Service
{

    private final static URL ALUNOWEBAUTHSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALUNOWEBAUTHSERVICE_EXCEPTION;
    private final static QName ALUNOWEBAUTHSERVICE_QNAME = new QName("http://ws2.exemplos.fiap.com/", "AlunoWebAuthService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://l2901micro04:8080/Exemplo3/AlunoWebAuthService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALUNOWEBAUTHSERVICE_WSDL_LOCATION = url;
        ALUNOWEBAUTHSERVICE_EXCEPTION = e;
    }

    public AlunoWebAuthService() {
        super(__getWsdlLocation(), ALUNOWEBAUTHSERVICE_QNAME);
    }

    public AlunoWebAuthService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALUNOWEBAUTHSERVICE_QNAME, features);
    }

    public AlunoWebAuthService(URL wsdlLocation) {
        super(wsdlLocation, ALUNOWEBAUTHSERVICE_QNAME);
    }

    public AlunoWebAuthService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALUNOWEBAUTHSERVICE_QNAME, features);
    }

    public AlunoWebAuthService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlunoWebAuthService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlunoWebAuth
     */
    @WebEndpoint(name = "AlunoWebAuthPort")
    public AlunoWebAuth getAlunoWebAuthPort() {
        return super.getPort(new QName("http://ws2.exemplos.fiap.com/", "AlunoWebAuthPort"), AlunoWebAuth.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlunoWebAuth
     */
    @WebEndpoint(name = "AlunoWebAuthPort")
    public AlunoWebAuth getAlunoWebAuthPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws2.exemplos.fiap.com/", "AlunoWebAuthPort"), AlunoWebAuth.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALUNOWEBAUTHSERVICE_EXCEPTION!= null) {
            throw ALUNOWEBAUTHSERVICE_EXCEPTION;
        }
        return ALUNOWEBAUTHSERVICE_WSDL_LOCATION;
    }

}
